

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      - SQLSERVER_IP=34.75.196.203
      - SQLSERVER_DB=app_db
      - SQLSERVER_USER=sqlserver
      - SQLSERVER_PASS=Minnu@123
    depends_on:
      - frontend

